### ISSUE TITLE
UI shows result much slower than it is generated

### ISSUE THREAD

**Issue by lbenedetto** [ollama-webui/ollama-webui#32]
**Describe the bug**
The UI looks like it is loading tokens in from the server one at a time, but it's actually much slower than the model is running. Sometimes it speeds up a bit and loads in entire paragraphs at a time, but mostly it runs painfully slowly even after the server has finished responding

In the console logs I see it took 19.5 seconds to generate the response:
```
ollama        | llama_print_timings:        load time =    1102.04 ms
ollama        | llama_print_timings:      sample time =     284.30 ms /  1027 runs   (    0.28 ms per token,  3612.33 tokens per second)
ollama        | llama_print_timings: prompt eval time =     273.78 ms /   146 tokens (    1.88 ms per token,   533.28 tokens per second)
ollama        | llama_print_timings:        eval time =   18724.47 ms /  1026 runs   (   18.25 ms per token,    54.79 tokens per second)
ollama        | llama_print_timings:       total time =   19506.92 ms
```

And in the network console in the browser, I see that the chunked response streamed in over the course of 21 seconds. 
However, the UI took several minutes to display the full prompt. During that time there was no further network traffic until the automatic prompt for the chat title.

**To Reproduce**
1. Run a prompt

**Expected behavior**
When the server is finished streaming the prompt to the client, the full prompt should be displayed. 

**Screenshots**
![image](https://github.com/ollama-webui/ollama-webui/assets/4466272/aaba66e9-5588-4d99-9afa-9908ab0db98f)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1
 - Browser: Vivaldi (Chromium based)
 - Version: Not sure, but here's my docker compose file:
 ```
version: '3.3'
services:
    ollama-webui:
        ports:
            - '3000:8080'
        container_name: ollama-webui
        image: ollamawebui/ollama-webui
    ollama:
        volumes:
            - './ollama:/root/.ollama'
        ports:
            - '11434:11434'
        environment:
            - 'OLLAMA_ORIGINS=*'
        container_name: ollama
        image: ollama/ollama
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
```
