### ISSUE TITLE
WebUI not Connecting to server

### ISSUE THREAD

**Issue by awptechnologies** [ollama-webui/ollama-webui#321]
after updating ollama webui i can no longer connect to my ollama instance. All settings are the same the only thing i changed is adding a volume for database. it says my server cant be connected. running latest image for ollama everything worked perfect until current build...

**Comment by awptechnologies** [comment]
just noticed when going to ollama url with /api i get 404. How do i ensure ollama api is being exposed

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue! Could you make sure that the ollama api url is set to `/ollama/api` in the webui settings? Also, try this alternative command: https://github.com/ollama-webui/ollama-webui/blob/main/TROUBLESHOOTING.md#ollama-webui-server-connection-error, Keep us updated, Thanks!

**Comment by awptechnologies** [comment]
Ollama is served through a reverse proxy since the instance runs on my servers not localhost. I was one of the original people to start using this and issue number 2 or 3 was helping me resolve my original issue. Ollama api is served from https://ollamaapi.mydomain.co/api. Before the update with the auth and account creation everything worked fine...

**Comment by awptechnologies** [comment]
OLLAMA_API_BASE_URL=https://example.com/api

I have this set as a build argument and in my webui settings it is indeed correct.

Offcourse the url is that of my personal domain but the variable i did pass through.

**Comment by tjbck** [comment]
Hmm, You're using `docker run -d -p 3000:8080 -e OLLAMA_API_BASE_URL=https://ollama.jryng.com/api -v ollama-webui:/app/backend/data --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main` command, and ollama api url is set to `/ollama/api` in the webui settings, correct?

**Comment by awptechnologies** [comment]
yes sir i will post my docker compose.
[Docker-Compose.txt](https://github.com/ollama-webui/ollama-webui/files/13795981/Docker-Compose.txt)

**Comment by tjbck** [comment]
Assuming both ollama and ollama-webui containers are running on the same machine, try this:

```
version: '3.9'

volumes:
  ollama-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.10.1.20,soft,rw"
      device: ":/mnt/marsSSD/Docker-Volumes/Ollama/ollama-data/_data/"
  ollamaui-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.10.1.20,soft,rw"
      device: ":/mnt/marsSSD/Docker-Volumes/Ollama/ollamaui-data/_data/"

services:
  app:
    image: ollama/ollama:latest
    volumes:
      - type: volume
        source: ollama-data
        target: /root/.ollama
        # volume:
          # nocopy: true
    ports:
      - "11434:11434"
    environment:
      OLLAMA_ORIGINS: "*"
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: "NVIDIA-GPU"
                value: 1
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.nas == true

  web:
    image: registry.lab.awptechnologies.co/ollama-webui:latest
    environment:
          - "OLLAMA_API_BASE_URL=http://app:11434/api"
    volumes:
      - type: volume
        source: ollamaui-data
        target: /app/backend/data
        # volume:
          # nocopy: true
    depends_on:
      - app
    ports:
      - "8040:8080"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.nas == true
```
