### ISSUE TITLE
docker compose webui connection issue

### ISSUE THREAD

**Issue by chymian** [ollama-webui/ollama-webui#41]
**Describe the bug**
webui has connection pbls., not showing models when  ollama server runs on docker.
true for running webui on docker or cli.

**To Reproduce**
docker-compose.yaml
```yaml
version: '3.6'

services:
  ollama-api:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: ollama/ollama:latest
    pull_policy: always
    container_name: ollama
    tty: true # enable colorized logs
    restart: unless-stopped
    environment:
      - OLLAMA_ORIGINS="*"
    ports:
      - 11434:11434
    volumes:
      - /var/lib/ollama:/root
      - /srv/models/ollama:/root/.ollama/models


  ollama-webui:
    restart: unless-stopped
    build:
      context: .
      args:
        OLLAMA_API_BASE_URL: 'http://ollama-api:11434/api'
      dockerfile: Dockerfile
    image: ollama-webui:latest
    container_name: ollama-webui
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3000:8080
```

**Expected behavior**
webui connects to ollama-api via internal docker routing.

**Server:**
 - OS: ubu22.04
 - Browser: ungoogled-chromium

**Additional context**
via  setup & build I have permutated many potenial URLs.
all (localhost, 0.0.0.0, VPN-IP) fail to connect-test, except using the LAN-IP.
but still shows no models.

`ollama list` works normal.
curl from another host via VPN also works.

__in the browser console log:__
IP: 10.11.1.x is VPN

```log
Access to fetch at 'http://10.11.1.17:11434/api/tags' from origin 'http://gulag:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
start.48f4feda.js:1     GET http://10.11.1.17:11434/api/tags net::ERR_FAILED
window.fetch @ start.48f4feda.js:1
$ @ 2.23ce0af1.js:316
h @ 2.23ce0af1.js:312
M @ 2.23ce0af1.js:316
2.23ce0af1.js:316 TypeError: Failed to fetch
    at window.fetch (start.48f4feda.js:1:1402)
    at $ (2.23ce0af1.js:316:30653)
    at h (2.23ce0af1.js:312:40212)
    at HTMLButtonElement.M (2.23ce0af1.js:316:343)
2.23ce0af1.js:316 null
192.168.178.17:11434/api/tags:1     Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
2.23ce0af1.js:316 TypeError: Failed to fetch
    at window.fetch (start.48f4feda.js:1:1402)
    at $ (2.23ce0af1.js:316:30653)
    at 2.23ce0af1.js:316:26530
    at v (scheduler.c37d1d9b.js:1:101)
    at Array.map (<anonymous>)
    at index.43b4ac03.js:4:2077
    at z (scheduler.c37d1d9b.js:1:1869)
    at _e (index.43b4ac03.js:4:3168)
    at new oe (app.4662c1c7.js:1:5070)
    at Pe (start.48f4feda.js:1:8373)
2.23ce0af1.js:316 null
```
IP: 192.168.178.x is LAN
```log
start.48f4feda.js:1     GET http://192.168.178.17:11434/tags net::ERR_CONNECTION_TIMED_OUT
window.fetch @ start.48f4feda.js:1
$ @ 2.23ce0af1.js:316
h @ 2.23ce0af1.js:312
M @ 2.23ce0af1.js:316
2.23ce0af1.js:316 TypeError: Failed to fetch
    at window.fetch (start.48f4feda.js:1:1402)
    at $ (2.23ce0af1.js:316:30653)
    at h (2.23ce0af1.js:312:40212)
    at HTMLButtonElement.M (2.23ce0af1.js:316:343)
2.23ce0af1.js:316 null
2.23ce0af1.js:316 []
2.23ce0af1.js:316 2e01853d-2963-421b-8629-e4cfef86baca
```
