### ISSUE TITLE
Ability to use Azure OpenAI endpoints

### ISSUE THREAD

**Issue by gregrobison** [ollama-webui/ollama-webui#437]
**Is your feature request related to a problem? Please describe.**
I am unable to get my Azure OpenAI API endpoint to be recognized - are there any additional settings needed?

**Describe the solution you'd like**
Azure OpenAI endpoint cannot connect.

**Describe alternatives you've considered**
API works in other environments. 

**Additional context**

**Comment by justinh-rahb** [comment]
If I had to guess, it's likely that ollama-webui needs to be able to send the `deployment_id` and `api_version` in the requests for Azure endpoints, which it currently does not have settings variables for.

**Comment by justinh-rahb** [comment]
One workaround you could do for the time being is using [LiteLLM](https://github.com/BerriAI/litellm) proxy to connect to your azure endpoint, and then connect ollama-webui to litellm. Here's their documentation on setting up Azure endpoints: https://litellm.vercel.app/docs/providers/azure

**Comment by anuraagdjain** [comment]
@tjbck  - Is the idea to provide support for other LLM endpoints via LiteLLM or have an explicit option for providing Azure OpenAI endpoint + key ?

**Comment by isaacblum** [comment]
I created this Ansible Playbook to address this exact need. Please take a look: https://github.com/SpaceTerran/ollama-webui_and_litellm

**Comment by justinh-rahb** [comment]
> I think a quick solution (temporary) could also be hardcoding the API version which gets added if the url contains the Azure domain. 
> This would skip the need to update the UI and probably can be done with a few lines of code.

Personally I wouldn't be against doing this in my own code but I think we can strive for higher here. If it's to be modified, is it much more additional work to do it right? Because I can see the issue reports now from that one guy that uses a different API version 😆

**Comment by Zulban** [comment]
I thought I'd write here in case others find it useful.

I was able to get Open WebUI (v0.1.118) to use Azure OpenAI, gpt4. I did this through litellm (1.35.5), my docker compose file is just a combination the four services: openwebui, postgresql, ollama, litellm. However one important gotcha is your litellm deployment cannot have a "LITELLM_MASTER_KEY" defined. Took me awhile to figure out. I'm still not sure how to get Open WebUI to use litellm with a LITELLM_MASTER_KEY. I'm still trying to determine this problem is:

* a bug, or
* a missing feature, or
* my mistake somewhere

**Comment by assinchu** [comment]
I am running litellm and trying to connect to Azure via litellm.
when i add the details in admin, it says connection is success, but when i ask questions, i am getting below error

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=14365): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1d183c6690>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by imbible** [comment]
@Zulban  @Michelklingler  How do you make Azure Dall-E 3 work via LiteLLM in WebUI? The Image setting does not provide an input field to specify the model.

**Comment by jakoberpf** [comment]
@Michelklingler I am currently trying to integrate some Azure OpenAI models with the liteLLM integration but somehow does not get it to work. Does my litellm config looks like this, but I am probably missing something. How did you get it to work?

```yaml
model_list:
  - model_name: gpt-4
    litellm_params:
      model: azure/test-gpt-4-turbo
      api_base: https://<azure-open-ai-service>.openai.azure.com/
      api_key: "<redacted>"
```

**Comment by Michelklingler** [comment]
> @Michelklingler I am currently trying to integrate some Azure OpenAI models with the liteLLM integration but somehow does not get it to work. Does my litellm config looks like this, but I am probably missing something. How did you get it to work?
> 
> ```yaml
> model_list:
>   - model_name: gpt-4
>     litellm_params:
>       model: azure/test-gpt-4-turbo
>       api_base: https://<azure-open-ai-service>.openai.azure.com/
>       api_key: "<redacted>"
> ```

Hey @jakoberpf !

Below is my config, works like a charm with Mistral-large and GPT4-Turbo

```
model_list:
- litellm_params:
    api_base: https://OpenAiEndpoint.openai.azure.com/
    api_key: e63b1d57d1ec42f9b04b522cd91d1b29
    model: azure/gpt4turbo
  model_info:
    id: f609d5af-7d43-45dc-81dd-b9c26212e259
  model_name: "Azure - GPT4-Turbo"
- litellm_params:
    api_base: https://Mistral-large-serverless.eastus2.inference.ai.azure.com/v1
    api_key: xxx
    model: mistral/Mistral-large
  model_info:
    id: ccaa5796-64f3-4691-b4a6-0598d2450ec7
  model_name: "Azure - Mistral-large"
```

I slightly change the link of the endpoint and removed the API key, but should work following this template!

Let me know if you get it work!
M.
