### ISSUE TITLE
Adding the supports for other models

### ISSUE THREAD

**Issue by mafrasiabi** [ollama-webui/ollama-webui#450]
I was wondering whether adding the support for other models e.g. from different endpoints like HuggingFace or AWS SageMaker is on the roadmap?

**Comment by justinh-rahb** [comment]
At the moment, the only external API format supported is OpenAI's. One workaround you could do is using [LiteLLM](https://github.com/BerriAI/litellm) proxy to connect to multiple different external APIs, and then connect ollama-webui to litellm. Here's their documentation: https://litellm.vercel.app/docs

And here's an example `docker-compose.yaml` I use to deploy both ollama-webui and litellm together in a stack:
```
version: '3.9'

services:
  webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    environment:
      - "OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}"
      - "OPENAI_API_BASE_URL=http://openai-proxy:8000/v1"
      - "OPENAI_API_KEY=${LITELLM_API_KEY}"
    ports:
      - 3000:8080
    volumes:
      - ./ollama-webui/data:/app/backend/data
    restart: unless-stopped

  openai-proxy:
    image: ghcr.io/berriai/litellm:main-latest
    environment:
      - "MASTER_KEY=${LITELLM_API_KEY}"
      - "OPENAI_API_KEY=${OPENAI_API_KEY}"
      - "MISTRAL_API_KEY=${MISTRAL_API_KEY}"
      - "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"
    ports:
      - 4000:8000
    volumes:
      - ./litellm/config.yaml:/app/config.yaml
    command: [ "--config", "/app/config.yaml", "--port", "8000" ]
    restart: unless-stopped
```
<img width="756" alt="294707599-1d027ac4-23d7-410e-a90e-64d497c512dc" src="https://github.com/ollama-webui/ollama-webui/assets/52832301/22799e68-3d30-44c0-a705-c9007750255b">
