### ISSUE TITLE
litellm config file

### ISSUE THREAD

**Issue by mafrasiabi** [ollama-webui/ollama-webui#562]
@justinh-rahb  Could you please share the litellm config file? I've been struggling to make it work but no matter what I did, I can't see the models on the model list

**Comment by justinh-rahb** [comment]
@mafrasiabi 
```yml
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo-1106
      api_base: https://api.openai.com/v1
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-4-turbo
    litellm_params:
      model: openai/gpt-4-1106-preview
      api_base: https://api.openai.com/v1
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: mistral-small
    litellm_params:
      model: mistral/mistral-small
      api_base: https://api.mistral.ai/v1
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: mistral-medium
    litellm_params:
      model: mistral/mistral-medium
      api_base: https://api.mistral.ai/v1
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: claude-2.1
    litellm_params:
      model: claude-2.1
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-instant-1.2
    litellm_params:
      model: claude-instant-1.2
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: cohere-command
    litellm_params:
      model: command
      api_key: "os.environ/COHERE_API_KEY"
  - model_name: cohere-command-light
    litellm_params:
      model: command-light
      api_key: "os.environ/COHERE_API_KEY"

general_settings:
  master_key: "os.environ/MASTER_KEY"
```

I got everything I know about configuring this from their docs:
https://docs.litellm.ai/docs/proxy/configs
