### ISSUE TITLE
GitHub Releases for Build version of this chat app?

### ISSUE THREAD

**Issue by coolaj86** [ollama-webui/ollama-webui#7]
I'm looking to create an installer for ollama for Webi (https://webinstall.dev), and some sort of UI like this (to make it more immediately accessible to people installing it).

Would you please release the pre-built version via GitHub Releases so that it can be used with just `ollama` and `caddy` without all of node?

## Automating Releases

I could help you get it so that basically when you `git tag v1.1.1 && git push --tags` a `.github/workflows` automatically builds and uploads it to the Releases section using [`gh`](https://webinstall.dev/gh/)

**Comment by tjbck** [comment]
Sounds good. After the #10 merge, could you add the files required to automate the process and create a separate pull request? Thanks a lot.

**Comment by coolaj86** [comment]
I probably won't have time to do that this week, but I'll make some notes now and get around to it when I can:

Here's how to publish locally with `gh`
- https://github.com/jmorganca/ollama/blob/main/scripts/publish.sh

There's already an action in the repo that goes through the build process:
- https://github.com/ollama-webui/ollama-webui/blob/main/.github/workflows/node.js.yaml#L3

This is what would be modified to create a workflow that operates on tags rather than branches:
```yaml
on:  
  push:
    tags:
      - '*'
```

All actions come with a `github.token` that can be assigned to scripts via ENVs:
```yaml
jobs:
    Build-GitHub-Pages:
        runs-on: ubuntu-20.04
        env:
          GH_BASIC_AUTH: "x-access-token:${{ github.token }}"
          GH_TOKEN: "${{ github.token }}"
```

I think what would be needed, however, is a token that specifically has either:
- `repo` (full repo access)
- > _Contents_ (read+write fine-grained control)
  > Repository contents, commits, branches, downloads, releases, and merges.

Much of my personal notes are at:
- <https://github.com/coolaj86/explore-github-actions/>
